---
title: "exam-4-study-guide"
author: Rick Gilmore
date: "`r Sys.time()`"
output:
  ioslides_presentation:
    css: css/gilmore.css
    incremental: false
    widescreen: true
  html_document:
    keep_md: true
    self_contained: false
bibliography: bib/bibliography.bib
---

## Prelude

<iframe width="560" height="315" src="https://www.youtube.com/embed/K8MWjFO9NCc" frameborder="0" allowfullscreen></iframe>

## Today's topics

- Review for Exam 4
- [Cerebral Symphony](https://rawgit.com/psu-psychology/psych-260/master/lectures/260-2016-12-09.html)

## History

- Descartes

## Methods

- Spatial/temporal resolution
- Structural/functional methods

## Anatomy

- Directional terms, slices
- Gross
    + Forebrain/midbrain/hindbrain
    + ventricles/CSF, meninges, blood supply
    + Gyri/sulci
    + lobes, insula/insular cortex
    + gray/white matter
    
## Cellular anatomy

- Parts of the neuron
    
## Neurophysiology

- Resting potential
    + force of diffusion, electrostatic pressure
- Action potential phases, causes/components
- Synaptic transmission
    + EPSPs, IPSPs
- Synaptic plasticity, LTP, NMDA receptors

## Neurochemistry

- Big Three -- Glu, GABA, ACh
- Neuromodulators -- DA, NE, 5-HT
- Hormones
    + Oxytocin, vasopressin

## Evolution and development

- History of life on Earth
- Vertebrates vs. non, humans vs. other vertebrates
- Prenatal vs. postnatal brain development

## Emotion

- Pleasure/reward system
- Fear, stress in behavior and brain

## Perception and Action

- Topographic maps: somatosensation, audition, vision
- Perceiving what vs. where: audition, vision
- Functional segregation: by receptor, type of info
- Receptive fields

## Memory

- Amnesia
- NMDA receptors and Hebbian learning
- Hippocampus size and memory demands