---
title: "260-2015-12-09-exam-4-review"
author: Rick Gilmore
date: "`r Sys.time()`"
bibliography: ../bib/bibliography.bib
output:
  ioslides_presentation:
    css: ../css/gilmore.css
    incremental: false
    widescreen: true
  html_document:
    keep_md: true
    self_contained: false
---

## Prelude

<iframe width="560" height="315" src="https://www.youtube.com/embed/K8MWjFO9NCc" frameborder="0" allowfullscreen></iframe>

## Announcements

## Today's topics

- Review for Exam 4

## Methods

- [Spatial/temporal resolution](https://cdn.rawgit.com/psu-psychology/psych-260/master/lectures/2015-08-31/260-2015-08-31-methods.html#5)
- [Structural/functional methods](https://cdn.rawgit.com/psu-psychology/psych-260/master/lectures/2015-08-31/260-2015-08-31-methods.html#6)

## Anatomy

- [Directional terms, slices](https://cdn.rawgit.com/psu-psychology/psych-260/master/lectures/2015-09-02/260-2015-09-02-anatomy-I.html#(4))
- Gross
    + [Forebrain/midbrain/hindbrain](https://cdn.rawgit.com/psu-psychology/psych-260/master/lectures/2015-09-02/260-2015-09-02-anatomy-I.html#(19))
    + [ventricles/CSF](https://cdn.rawgit.com/psu-psychology/psych-260/master/lectures/2015-09-02/260-2015-09-02-anatomy-I.html#(12)), [meninges](https://cdn.rawgit.com/psu-psychology/psych-260/master/lectures/2015-09-02/260-2015-09-02-anatomy-I.html#(11)), blood supply
    + [Gyri/sulci](https://cdn.rawgit.com/psu-psychology/psych-260/master/lectures/2015-09-04/260-2015-09-04-anatomy-II.html#5)
    + [gray/white matter](https://cdn.rawgit.com/psu-psychology/psych-260/master/lectures/2015-09-04/260-2015-09-04-anatomy-II.html#7)
    
## Cellular anatomy

- [Parts of the neuron](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-09-11/260-2015-09-11-cells.html#17)
    
## Neurophysiology

- [Resting potential](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-09-14/260-2015-09-14-neurophys-I.html#15)
- Action potential [phases](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-09-18/260-2015-09-18-neurophys-II.html#16), [components](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-09-18/260-2015-09-18-neurophys-II.html#18)
- [Synaptic transmission](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-09-30/260-2015-09-30-neurochem-II.html#7)
- [Hebbian learning](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-12-02/260-2015-12-02-learning-memory-I.html#12), [Synaptic plasticity, LTP, NMDA](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-12-02/260-2015-12-02-learning-memory-I.html#13)

## Neurochemistry

- Big Three -- [Glu](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-09-30/260-2015-09-30-neurochem-II.html#9), [GABA](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-09-30/260-2015-09-30-neurochem-II.html#11), [ACh](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-09-30/260-2015-09-30-neurochem-II.html#14)
- Neuromodulators -- [DA](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-09-30/260-2015-09-30-neurochem-II.html#26), [NE](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-09-30/260-2015-09-30-neurochem-II.html#30), [5-HT](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-09-30/260-2015-09-30-neurochem-II.html#34)

## Evolution and development

- [History of life on Earth](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-09/260-2015-10-09-evo.html#13)
- [Vertebrates vs. non](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-09/260-2015-10-09-evo.html#15), [humans vs. other vertebrates](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-09/260-2015-10-09-evo.html#19)
- [Prenatal vs. postnatal brain development](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-12/260-2015-10-12-devel.html#3)

## Biological rhythms and sleep

- [REM vs. other phases](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-07/260-2015-10-07-sleep.html#16)
- [SCN, pineal gland, melatonin](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-07/260-2015-10-07-sleep.html#7)

## Emotion

- [Pleasure/reward system](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-19/260-2015-10-19-emotion.html#29)
- Fear, stress in [behavior](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-21/260-2015-10-21-fear-stress.html#6) and [brain](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-21/260-2015-10-21-fear-stress.html#8)

## Perception and Action

- Topographic maps: [somatosensation](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-04/260-2015-11-04-somatosensation.html#17), [audition](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-11/260-2015-11-11-audition.html#27), [vision](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-16/260-2015-11-16-vision-II.html#18)
- Perceiving what vs. where: [audition](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-11/260-2015-11-11-audition.html#31), [vision](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-16/260-2015-11-16-vision-II.html#32)
- Functional segregation: by receptor, type of info
- Receptive fields

## Next time

- The Cerebral Symphony