---
title: "260-2015-11-18-review"
author: Rick Gilmore
date: "`r Sys.time()`"
output:
  ioslides_presentation:
    css: ../css/gilmore.css
    incremental: false
    widescreen: true
  beamer_presentation:
    pandoc_args: [
      "--latex-engine=xelatex"
    ]
  slidy_presentation: default
  pdf_document: default
  md_document: default
  html_document:
    keep_md: true
---

## Today's Topics

- Exam 3 review

## [Emotion](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-19/260-2015-10-19-emotion.html)

- [Components](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-19/260-2015-10-19-emotion.html#6)
- [Plutchik's biological approach](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-19/260-2015-10-19-emotion.html#7)
- ["Outputs" of emotional computing](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-19/260-2015-10-19-emotion.html#19)
- [Reward circuitry](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-19/260-2015-10-19-emotion.html#29)


## [Fear and stress](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-21/260-2015-10-21-fear-stress.html)

- [Learned fear](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-21/260-2015-10-21-fear-stress.html#6)
- [Normal vs. abnormal stress response](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-21/260-2015-10-21-fear-stress.html#19)

## [Psychopathology](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-23/260-2015-10-23-psychopathology-I.html)

- [Depression](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-23/260-2015-10-23-psychopathology-I.html)
    + [Neurological factors](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-23/260-2015-10-23-psychopathology-I.html#8)
    + [Pharmacological factors](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-23/260-2015-10-23-psychopathology-I.html#17)
    
## [Psychopathology](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-26/260-2015-10-26-psychopathology-II.html)

- [Bipolar disorder](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-26/260-2015-10-26-psychopathology-II.html#8)
    + [Neurological factors](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-26/260-2015-10-26-psychopathology-II.html#12)
    + [Pharmacological factors](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-26/260-2015-10-26-psychopathology-II.html#17)
- [Schizophrenia](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-26/260-2015-10-26-psychopathology-II.html#22)
    + [Neurological factors](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-26/260-2015-10-26-psychopathology-II.html#30)
    + [Pharmacological factors](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-10-26/260-2015-10-26-psychopathology-II.html#33)
    
## [Sensory systems](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-02/260-2015-11-02-sensation.html)

- [Interceptive/Exteroceptive](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-02/260-2015-11-02-sensation.html#11)
- [Features of sensory systems](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-02/260-2015-11-02-sensation.html#19)
- [Frequency sensitivity](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-02/260-2015-11-02-sensation.html#21)
- [Compare signals between sensors](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-02/260-2015-11-02-sensation.html#23)
- [Receptive fields](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-02/260-2015-11-02-sensation.html#25)
- [Topographic maps](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-02/260-2015-11-02-sensation.html#28)
- [Acuity non-uniform](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-02/260-2015-11-02-sensation.html#31)
- [Hierarchical and parallel processing](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-02/260-2015-11-02-sensation.html#35)

## [Somatosensation](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-04/260-2015-11-04-somatosensation.html)

- [Types](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-04/260-2015-11-04-somatosensation.html#5)
- [Specialized cutaneous receptors](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-04/260-2015-11-04-somatosensation.html#9)
- [Combined thermo- and chemoreceptors](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-04/260-2015-11-04-somatosensation.html#11)
- [Size/speed trade-off](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-04/260-2015-11-04-somatosensation.html#13)
- [From skin to brain](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-04/260-2015-11-04-somatosensation.html#14)

## [Audition](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-11/260-2015-11-11-audition.html)

- [Detecting sound](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-11/260-2015-11-11-audition.html#7)
- [Place coding of frequency](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-11/260-2015-11-11-audition.html#26)
- [From ear to brain](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-11/260-2015-11-11-audition.html#22)
- [Coding direction, elevation](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-11/260-2015-11-11-audition.html#32)

## Vision

- [The eye](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-13/260-2015-11-13-vision-I.html)
- [The biological camera](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-13/260-2015-11-13-vision-I.html#16)
- [Fovea vs. periphery](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-13/260-2015-11-13-vision-I.html#25)
- [Photoreceptors](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-13/260-2015-11-13-vision-I.html#28)
- [Receptive fields](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-16/260-2015-11-16-vision-II.html#8)
- [Color opponency](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-16/260-2015-11-16-vision-II.html#11)
- [From eye to brain](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-16/260-2015-11-16-vision-II.html#13)
- [Retinotopy](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-16/260-2015-11-16-vision-II.html#21)

## Vision

- [Laminar/columnar organization](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-16/260-2015-11-16-vision-II.html#23)
- [Dorsal/ventral stream](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-16/260-2015-11-16-vision-II.html#32)

## Action

- [Types of actions](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-06/260-2015-11-06-action-I.html#8)
- [Muscle classes](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-06/260-2015-11-06-action-I.html#11) and [types](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-06/260-2015-11-06-action-I.html#13)
- [How muscles contract](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-06/260-2015-11-06-action-I.html#15)
- [Myotatic/stretch reflex](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-09/260-2015-11-09-action-II.html#5)
- Axon size/speed trade-off
- [How the brain controls the muscles](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-09/260-2015-11-09-action-II.html#14)
- [Parkinson's](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-09/260-2015-11-09-action-II.html#20) and [Huntington's](https://rawgit.com/psu-psychology/psych-260/master/lectures/2015-11-09/260-2015-11-09-action-II.html#22)

